#!/bin/bash
# Futur addition generate msfvenom payload but i will make an other project for that so stay tuned
#read -p "Do you want to generate a metasploit payload [Y/n]" msf_choice
#    if [[ $msf_choice == Y || $msf_choice == y ]];then
#      curl -k -L "https://raw.githubusercontent.com/g0tmi1k/mpc/master/msfpc.sh" > /tmp/msfpc.sh && sudo mv /tmp/msfpc.sh /usr/local/bin && sudo chmod +x /usr/bin/msfpc.sh;


help_banner=$(echo "Usage : sudo ./ebowla payload_to_encode.exe output_encoded.exe [Optional argument: --nohidden]")

if [[ $1 == -h || $1 == --help ]];then
    echo $help_banner
elif [[ -z $1 || -z $2 ]]; then
    echo $help_banner
else
    read -p "Set the path to Ebowla directory (default: /pentest/av-bypass/Ebowla): " ebowla

if [ ! $ebowla ]; then
    cd /pentest/av-bypass/Ebowla_perso/
else
    cd "$ebowla"
fi

echo "$PWD"

filename1=$(basename $1)

read -p "Do you want to configure the genetic.config file ? [Y/n]: " genetic
    if [[ $genetic == Y || $genetic == y ]];then
        sudo vi genetic.config;
    else
        echo "Ok?! Let's jump it!!"
    fi
        
read -p "Configure the arch of your payload [x86/x64] :" arch
        if [[ $arch == x64 && -z $3 ]]; then
            sudo ./ebowla.py $1 genetic.config;
            sudo ./build_x64_go.sh output/go_symmetric_$filename1.go $2;
            echo "Job done! All have been saved under $ebowla/output directory"
            exit 1;
        elif [[ $arch == x86 && -z $3 ]];then
            sudo ./ebowla.py $1 genetic.config;
            sudo ./build_x86_go.sh output/go_symmetric_$filename1.go $2;
            echo "Job done! All have been saved under $ebowla/output directory"
            exit 1;
        elif [[ $arch == x64 && $3 == --nohidden ]]; then
            sudo ./ebowla.py $1 genetic.config;
            echo "--nohidden detected"
            sudo ./build_x64_go.sh output/go_symmetric_$filename1.go $2 $3; 
            echo "Job done! All have been saved under $ebowla/output directory"
            exit 1;
        elif [[ $arch == x86 && $3 == --nohidden ]];then
            sudo ./ebowla.py $1 genetic.config;
            echo "--nohidden detected"
            sudo ./build_x86_go.sh output/go_symmetric_$filename1.go $2 $3; 
            echo "Job done! All have been saved under $ebowla/output directory"
            exit 1;
        else
            echo "Without the good choice we cant do the job!! Bye!!"
            exit 0;
        fi
fi
